### ISSUE TITLE
Cannot Repair

### ISSUE THREAD

**Issue by DanielJRamirez** [gianlucacini/ForceDNS#1]
Was cleaning out PC and haphazardly deleted the ForceDNS UI file. I attempted to run the repair installer again to correct this, but it got stuck on "Stopping services Service [1]". After sitting still for several minutes, an error message came up saying that ForceDNS settings could not be stopped. Is there any way to get the UI back?

**Comment by gianlucacini** [comment]
try and kill it from the task manager. If you can't kill it it means forcedns is still running and you have to wait till the timer you set runs out.

**Comment by DanielJRamirez** [comment]
Alright, thank you for the timely reply.
